#!usr/bin/env bash
#This script print Best School ten time, On the 9th time it prints hi

count=0

while [ $count - lt 10]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
