#!/usr/bin/env bash
#  This script display:
#  The content of the current directory
#  In a list format
#  Where only the part of the name after the first dash is displayed

for f in *
do
	if [[ -f $file && $file != .* && $file =~ ^[^-]*- ]]
       	then
		 echo "${file#*-}"
	fi
done
